# Generated by Django 5.0 on 2023-12-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Mail",),
    ]
