# Generated by Django 5.0 on 2023-12-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_delete_mail"),
    ]

    operations = [
        migrations.RemoveField(model_name="sms", name="sms",),
        migrations.AddField(
            model_name="sms",
            name="label",
            field=models.CharField(default="Not Predicted", max_length=100),
        ),
    ]
