# Generated by Django 5.0 on 2023-12-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mail",
            name="label",
            field=models.CharField(default="Not Predicted", max_length=100),
        ),
    ]
