# Generated by Django 5.0 on 2023-12-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_mail_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail", name="mail", field=models.CharField(max_length=10000),
        ),
    ]
